### ISSUE TITLE
Calculators GP tool missing CalculateStripMap

### ISSUE THREAD

**Issue by anthonyryan-ergon** [Esri/product-on-demand#13]
Hi there,

With Calculators GP tool missing CalculateStripMap task, what changes to POD (eg. podconfig.js, etc.) is required if any to function correctly?

Thanks

**Comment by Madhura02** [comment]
@aryan200o trying to clarify - are you reporting that the CalculateStripMap task is missing in the Calculators.sd file? I am trying to understand if there was an error with publishing or if this was removed by intention. If not intentional then I suggest re-publish to see if its still reproducible.

**Comment by anthonyryan-ergon** [comment]
Madhura2,
Yes. I am able to publish with no errors and can be repeated. I download the zip file again today and republished with the same result.

Attached is a screenshot of the service's rest page.
![calculator](https://cloud.githubusercontent.com/assets/19471219/20692149/cdac1cf4-b621-11e6-98fb-38a7776b2b84.png)


Thank you for looking at this

**Comment by Madhura02** [comment]
Hi @aryan200o, 

Thank you for responding and sending the screenshot. Now I understand that service definition you have used is from the master-branch zip. We have made some changes to the master branch since the release and therefore you don't see the CalculateStripMap task in this branch. Release1 available at https://github.com/Esri/product-on-demand/releases will have the task in the service definition. 

From what I can tell if you want to use the services from the master branch you will need to remove or comment out "gpCalculateStripMapUrl" from podconfig.js and from the "required" attributes list in ConfigurationSchema.js. If you dont want to make changes to your local javascript files then I would suggest to use the files from the Released package. This should resolve the issue. Hope this helps. Let me know if there are more questions.

**Comment by anthonyryan-ergon** [comment]
Madhura2,
Thankyou for your help. I've deployed POD using Release 1 and currently modifying it to use a local version of the js api.
